name: Generate GitHub Stats Image

on:
    schedule:
        - cron: "0 0 * * *" # Ejecuta una vez al día
    workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Generate GitHub Stats
              run: |
                  curl -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
                       "https://github-readme-stats.vercel.app/api?username=ArnoldBF&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight" \
                       --output assets/stats.svg

            - name: Commit and push
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add assets/stats.svg
                  git commit -m "🔄 Update GitHub stats" || echo "No changes to commit"
                  git push
